import { Figtree, Roboto } from "next/font/google";
import "./globals.css";

const figtree = Figtree({
  subsets: ["latin"],
});
const roboto = Roboto({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${figtree.variable} ${roboto.variable} antialiased`}>
        <main>{children}</main>
      </body>
    </html>
  );
}
